FROM node:14.6.0

MAINTAINER daizch <daizech@gmail.com>

RUN mkdir -p /data/fe-micro-server

WORKDIR /data/fe-micro-server

COPY . /data/fe-micro-server

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5001

EXPOSE 5001

CMD [ "npm", "start" ]