FROM node:14.14.0

MAINTAINER daizch <daizech@gmail.com>

RUN mkdir -p /data/fe-micro-server

WORKDIR /data/fe-micro-server

COPY . /data/fe-micro-server

RUN npm install --production

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 5001

EXPOSE 5001

CMD [ "npm", "start" ]